### ISSUE TITLE
4.3.0-rc1 causes sls deploy stucked

### ISSUE THREAD

**Issue by gs-jackal** [FidelLimited/serverless-plugin-warmup#123]
The latest tag 4.3.0-rc1 makes `sls deploy` stucked in a loop.

strace shows infinite futex() syscall causing sls to stuck in 100% CPU usage.

**Comment by juanjoDiaz** [comment]
Thanks for reporting!

I'll take a look asap.
Which version of serverless are you using?

**Comment by gs-jackal** [comment]
Hi, I'm using the latest serverless version 1.37.1

**Comment by juanjoDiaz** [comment]
Hi,

I've been testing and don't have any problem deploying with `4.3.0-rc1`.
Can you elaborate a bit more on your scenario?
Are you using other plugins that might be creating the issue.
Do you get any error details?

**Comment by gs-jackal** [comment]
Hmm.. that's strange because I only have problem with the latest version but rolling back to 4.2.0-rc1 works fine.

Here's the plugins I'm using:
```
plugins:
  - serverless-domain-manager
  - serverless-plugin-warmup
  - serverless-python-requirements
  - serverless-wsgi
```

There's no error but `sls deploy` stucked there forever utilizing 100% CPU if using 4.3.0-rc1.

**Comment by juanjoDiaz** [comment]
Have you tried verbose mode to see if you can get more useful logs: `sls deploy --verbose`??

**Comment by gs-jackal** [comment]
Hi @juanjoDiaz  it's the same as well.. here's the result

```
ssteo@lab:~/private/xxx-lambda$ sls deploy --verbose
(hanging there forever)
```
the process `node /usr/local/bin/sls deploy --verbose` PID is 6708

My package.json below:
```
{
  "name": "x-webapp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless-domain-manager": "^2.6.13",
    "serverless-plugin-warmup": "^4.3.0-rc.1",
    "serverless-python-requirements": "^4.2.5",
    "serverless-wsgi": "^1.7.1"
  }
}```

And here's the result of `strace -p 6708`... just keep repeating with futex() calls.. reverting to 4.2.0-rc1 works fine.

```
strace: Process 6708 attached
strace: [ Process PID=6708 runs in x32 mode. ]
strace: [ Process PID=6708 runs in 64 bit mode. ]
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7ffc74668fa8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x7ffc74668fb0, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x7ffc74668fb0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7ffc74668fac, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x7ffc74668fb0, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x7ffc74668fb0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7ffc74668fa8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x7ffc74668fb0, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x7ffc74668fb0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7f618, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff) = 0
futex(0x560421e7f618, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff) = 0
write(8, "\1\0\0\0\0\0\0\0", 8)         = 8
getpid()                                = 6708
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
mmap(0x2e2d99500000, 2109440, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x2e2d99500000
munmap(0x2e2d99683000, 524288)          = 0
mmap(0x2e2d99500000, 1585152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2e2d99500000
write(8, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421ebf1a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d0c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560421e7d070, FUTEX_WAKE_PRIVATE, 1) = 1
```

**Comment by juanjoDiaz** [comment]
Thanks for the details!

This is really strange...

The futex is a Linux kernel system call used by threading implementations, like libpthread, to implement mutexes, semaphores, and all that. This library us pure javascript and doesn't use any of such low-level APIs...

Some quick googling shows similar issues happening on endless loops and stuff like that but mostly using node 0.10. What node version are you using?
So it's likely that there is an endless loop or something like that being created somewhere. Maybe this is related to #117 except that you are replicating it consistently...

Would you mind sharing your warmup config? So I can try to replicate the issue.

I just released 4.3.1-rc1. You can try it, although I'd expect  the same results as in 4.3.0-rc1 🙂

**Comment by juanjoDiaz** [comment]
It might be the python or wsgi plugin screwing the warmer lambda.
Plugins are executed in the order that you declare them. Those two plugins come after the warmup one so they might be picking it as one of your declared function. (Just a wild guess...)

Have you tried to place this plugin the last one?
```yaml
plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-plugin-warmup
```

**Comment by gs-jackal** [comment]
Hi, my node version is 8.10.0 running on
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

I've tried switching the sequence of the plugins either placing at the first or last is the same. Tried 1.31.-rc1 same as well.

My warmup config, note that it is still using `default` and `schedule` as version after 4.2.0 doesn't recognize `enable` and `event`. I've tried 

```
  warmup:
    default: true
    schedule: rate(4 minutes)
    prewarm: true
    role: IAMRoleServerlessWarmer
```

**Comment by gs-jackal** [comment]
By the way, I could also reproduce the issue on my local Mac running this version.

`Darwin xx.gs24.com 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

I've tried to compare the changes but unfortunately there are too many changes between 4.2.0-rc1 and 4.3.0-rc1. Maybe can release more often in future with smaller changes?

**Comment by gs-jackal** [comment]
Nevertheless, I believe the futex() deadlock has something to do with the Promises/await behaviour
https://thecodebarbarian.com/mutual-exclusion-patterns-with-node-promises

bluebird npm module probably has some difference in behaviour..? I'm unsure, I'm a Python guy not so deep into Javascript stack.

**Comment by juanjoDiaz** [comment]
Agreed. The project went a bit stale after 4.2 and then I took over. The intention now is to move to `5.0.0` and keep releasing often.

It weird that there aren't any unhandled promises reported by jest and no one else is seeing this issue. But I'll keep trying to replicate it.

There seem to be many issues on the serverless repo related to endless loops and 100% CPU.
Can you run `serverless package` with `4.3.X-rc.1`? If not, it might be a problem with the env variables as described in https://github.com/serverless/serverless/issues/3882 or https://github.com/serverless/serverless/issues/5275. Or maybe is stuck in a retry loop like https://github.com/serverless/serverless/issues/5241?

**Comment by juanjoDiaz** [comment]
Might this be related to #126??
Are you using env vars like in the warmup config?

**Comment by gs-jackal** [comment]
Hi, I've just tested `sls package` stucked as well. Looks like related to 
https://github.com/serverless/serverless/issues/3882 and  https://github.com/serverless/serverless/issues/5275

**Comment by sgraup** [comment]
I'm having the same issue. Any sls plugin {install,uninstall,list} hangs after the warmup plugin has been installed. Deleting the node_modules, package-lock.json and package.json files "fixes" the issue. Installing the warmup plugin last is a temporary solution, but causes issues if you continue to develop and try to interact with plugins after that. I have removed the warmup plugin from my project until this is resolved.

**Comment by juanjoDiaz** [comment]
Can you try 4.3.2-rc.1 and reopen if the issue persists?
The problem seemed to be caused by https://github.com/serverless/serverless/pull/3911

Not sure what's the impact of installing the modules in a different order... that's definitely strange... :/

**Comment by gs-jackal** [comment]
Hi, just tried 4.3.2-rc1 it's the same as well.

**Comment by gs-jackal** [comment]
@juanjoDiaz  Honestly, I think closing this issue is not the best way to resolve this as other plugins have no issue and older version works fine. But later version starts to have this issue after major code changes.

I reviewed my serverless.yml also has no cyclic reference.

**Comment by juanjoDiaz** [comment]
Hummm

If I could just replicate this... 😞 
I'll keep trying...

**Comment by juanjoDiaz** [comment]
Could you try to create a hello world so I can replicate this?

I've tried everything (including copying your config and uninstall and install dependencies as suggested by @sgraup) and just can't get this to happen in any of my projects.

**Comment by ssteo** [comment]
Ok, I'll try to create a separate app. tonight and if it can be replicated, will share it over.

**Comment by sgraup** [comment]
Hello,

This is the list of other plugins we're using with our deployments:

  - serverless-aws-documentation
  - serverless-api-stage
  - serverless-reqvalidator-plugin
  - serverless-pseudo-parameters

If I include the warmup plugin anywhere but last in this list, the next plugin will hang during installation. After the warmup plugin is installed things like sls plugin list also hang. Perhaps there is a conflict with the warmup plugin and one of these other plugins. As I mentioned, removing all the npm files in the directory rectifies the problem until the warmup plugin is re-installed.

We're using serverlss 1.37.1

**Comment by gs-jackal** [comment]
Hi @juanjoDiaz  here's the project, can reproduce everytime with this https://github.com/gs-jackal/sls-plugin-warmer-bug-reproduce

If you change it to version 4.2.0-rc1 with a valid AWS account ID, ARN for certificate and domain name. It will work.

**Comment by gs-jackal** [comment]
Just a note, the project is setting `createRoute53Record` to false because I use CloudFlare, but using route53 should work if you have a free domain in route53.

**Comment by juanjoDiaz** [comment]
Thanks, guys!
I could reproduce it with @gs-jackal repo.

The problem was caused by a combination of https://github.com/serverless/serverless/pull/3911 and https://github.com/serverless/serverless/issues/2631.
Basically, serverless doesn't resolve options properly and doesn't resolve variables at constructor time.
Inferring the stage and region at constructor time was causing an endless loop within serverless for some reason (maybe I should just create a ticket in serverless about it since it should error and never go into endless loops no matter what).

Can you try 4.3.3-rc.1 and see if the issue is resolved?

**Comment by gs-jackal** [comment]
Thanks @juanjoDiaz , works great now!
