### ISSUE TITLE
[4.3.0+] Plugin does not properly handle variables

### ISSUE THREAD

**Issue by Kivol** [FidelLimited/serverless-plugin-warmup#126]
From version 4.3.0, I see the following error on deployment:

```
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [env:STAGE] in the Resources block of the template
```

By investigating `cloudformation-template-update-stack.json`, I see the warmup plugin mishandles the `${env:FOO}` or `${opt:BAR}` variables by setting function name like:

```
"FunctionName": "my-project-${env:STAGE}-warmup-plugin",
```

This behavior happens from v4.3.0, while v4.2.0 works fine.

**Comment by juanjoDiaz** [comment]
Can you try 4.3.2-rc.1 and reopen if the issue persists?
The problem seemed to be caused by https://github.com/serverless/serverless/pull/3911
