### ISSUE TITLE
4.3.x-rc1 causes sls deploy stucked

### ISSUE THREAD

**Issue by gs-jackal** [FidelLimited/serverless-plugin-warmup#131]
Tested everything stated in https://github.com/FidelLimited/serverless-plugin-warmup/issues/123

Unable to reopen back the same ticket, also I don't use any Ref in my serverless template so unlikely this https://github.com/serverless/serverless/pull/3911 cause the problem.

**Comment by juanjoDiaz** [comment]
#123 is reopened so I'll close this to avoid the duplicate.
