### ISSUE TITLE
Skip warmup if event source is not http

### ISSUE THREAD

**Issue by ndeitch** [FidelLimited/serverless-plugin-warmup#146]
Hi Guys,

Thanks for this plugin.

In my company scenario, We don't want to enable warmup if function is not invoked through API Gateway, I was thinking to create an option that enables warmup only for HTTP event type.

This make sense to you?

Edit: I was reading the docs again, and see that I can set warm per function, it resolves my issue, but do you think that even though make sense create a PR for it?

**Comment by juanjoDiaz** [comment]
The use case makes sense and it's fairly common.
As you already noticed, it can be done setting a lambda per function.

What would be the advantage of being able to flag a specific handler type? Just to be less verbose? 

I'm not 100% convinced that it's needed but I wouldn't be completely opposed to being able to select which lambdas to warm up based on the handler as long as it's generic enough.

At the moment the `enabled` option can be a boolean, a stage or a list of stages.
Maybe it could be also an object like:
```js
{
  stages: [...], // stage or array of stages
  handlers: [...] // handler or array of handlers
}
```
???

**Comment by ndeitch** [comment]
We were thinking that is interesting warmup http functions because they impact directly our customers, and disable for functions that will be invoked by s3, sqs, etc.
Not sure about the value of this feature because I can achieve this by enabling/disabling per function, I see no problem in closing this issue, what do you think?

**Comment by juanjoDiaz** [comment]
Sorry for the slow response!

Let's close this for now since, as you mentioned, the use case is easily achievable enabling/disabling per function.

We can always come back to it if more similar use cases would come up. 🙂

**Comment by ndeitch** [comment]
Agreed!

Thanks for your attention!
