### ISSUE TITLE
Node6.10 is deprecated at AWS lambda

### ISSUE THREAD

**Issue by domdetre** [FidelLimited/serverless-plugin-warmup#152]
As of June 30, 2019 AWS deprecated and shut down nodejs version 6.10

```
ServerlessError: An error occurred: WarmUpPluginLambdaFunction - The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions.
```

https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

**Comment by juanjoDiaz** [comment]
This plugin uses node 8.10 since version 4.0.0.

Please update your dependency.

**Comment by domdetre** [comment]
My bad, somehow I missed the wrong version I had, apologies.....

BTW in the README.md in one example it shows node6.10, I know that is just an example, but would be nice if it would be updated to 8.10.

**Comment by EGrun** [comment]
This issue was useful to me as it explained why some of our lambdas stopped deploying.
