### ISSUE TITLE
Get event source for python flask

### ISSUE THREAD

**Issue by ptrhck** [FidelLimited/serverless-plugin-warmup#156]
I am keeping a Python Flask API hot with this plugin. Now, I would like to get the event source as proposed in the docs. On this account, the [serverless-wsgi](https://github.com/logandk/serverless-wsgi#raw-context-and-event) plugin suggests that you can get it as follows:

```
from flask import Flask, request
app = Flask(__name__)


@app.route("/")
def index():
    print(request.environ['serverless.context'])
    print(request.environ['serverless.event'])
```

However, the logs do not show anything if the function is invoked by the warmup-function. Is the endpoint simply not invoked, but only the lambda code itself?

I would appreciate some help to get this done in Python.

**Comment by juanjoDiaz** [comment]
From what I can see in the readme, the serverless-wsgi plugin ignore requests from this plugin (https://github.com/logandk/serverless-wsgi/blob/c14f257b1f12f6db1152430d23c948715803c2b9/README.md)

The actual code is here: https://github.com/logandk/serverless-wsgi/blob/3a2d1312370a4f4351be60f5fbe838124db1916a/serverless_wsgi.py#L87

**Comment by ptrhck** [comment]
I did not see that, thank you! Would be great to get some log that it was invoked from this plugin though.

**Comment by juanjoDiaz** [comment]
I agree. However, that's something that needs to be done on the serverless-wsgi plugin. So you should ask there.

**Comment by juanjoDiaz** [comment]
Closing this since the relevant issue is already open in the serverless-wsgi plugin repo.

Feel free to reopen if you think that there is still anything else for us to do.
