### ISSUE TITLE
Environment variables not supported in AWS China Deployment

### ISSUE THREAD

**Issue by robertmorgan** [FidelLimited/serverless-plugin-warmup#158]
Currently when you try to deploy the function created by the plugin to one of AWS' Chinese regions (`cn-north-1` & `cn-northwest-1`), the creation will fail in CloudFormation because Environment Variables are not supported in those regions.

This plugin creates an empty object in the CloudFormation template - even if no variables are specified.

You can work around this by specifying the plugin's `environment` option to be `null` in your serverless.yml configuration

It would be nice to not have to find this through trial an error, there are a few routes which could be looked into:

1. Add a note regarding deployment in China to the README
2. Don't write out an empty object to the template if there are no variables specified.
3. Inspect the region and error if any environment varaibles are defined for the Chinese regions.

**Comment by juanjoDiaz** [comment]
Sorry for the radio silence. I totally missed this.
But I've now implemented option 2 (don't write anything if the object is empty) and I'll push it soon.
