### ISSUE TITLE
Keep switching back to Node runtime 6.10

### ISSUE THREAD

**Issue by saachinsiva** [FidelLimited/serverless-plugin-warmup#167]
Hello

We have a new serverless app written in node and we use node 10.x as the runtime in the yml , however when we do sls, we get the below error. Please advise

Serverless version : 1.46.0
serverless-plugin-warmup: ^3.6.2-rc.1

>   Serverless Error --------------------------------------- 
>   
>   An error occurred: WarmUpPluginLambdaFunction - The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 27e22f24-99ac-11e9-933c-fb02c599544a). 
>   
>   Stack Trace -------------------------------------------- 
>   
> ServerlessError: An error occurred: WarmUpPluginLambdaFunction - The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 27e22f24-99ac-11e9-933c-fb02c599544a).

**Comment by juanjoDiaz** [comment]
Hi @saachinsiva ,
You are using a very old version of the plugin which used node 6.
You should update to a newer version. 4.0.0-rc.1 switched to node 8 and the latest 4.6.3-rc.1 switched to node 10. I'd recommend using always the latest version.

**Comment by saachinsiva** [comment]
@juanjoDiaz 

Thank your help. I did not realize that we were using very old version. I updated the package and it works fine.
