### ISSUE TITLE
Getting WarmupPlugin run time nodejs6.10

### ISSUE THREAD

**Issue by vlad-traceme** [FidelLimited/serverless-plugin-warmup#168]
@juanjoDiaz i am using 

"serverless-plugin-warmup": "4.6.3-rc.1",

We are currently on node10x and plugin seems to always default to nodejs6.10

and still getting this error:
  An error occurred: WarmUpPluginLambdaFunction - The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 17d7be97-9d20-11e9-a4b4-9f60793ab94d).

**Comment by vlad-traceme** [comment]
I had to disable the plugin for AWS to clean the lambda / logs etc, then I re-enabled it and it was finally able to pick up the upgraded package runtime, super weird

**Comment by juanjoDiaz** [comment]
Hi @vlad-traceme ,

That's weird indeed.
It should definitely pick up the correct node and redeploy if needed. Maybe it's a bug on the Serverless framework or in CloudFormation? No idea...

Glad that you found a workaround.

**Comment by vlad-traceme** [comment]
I think it has to do with them just completely deprecating node 6.10 this week so heads up for anyone that has this weird behavior. Upgrade from 8.10 to 10x run time on this plugin worked flawlessly. Thanks @juanjoDiaz

**Comment by rbjoshi** [comment]
Hi @vlad-traceme 

I am new to this and getting the same issue.
How can I solve this?

Thanks

**Comment by vlad-traceme** [comment]
@rbjoshi I switched to using webpack which works flawlessly with typescript

**Comment by juanjoDiaz** [comment]
@rbjoshi the version used by the plugin is given by the plugin version.
Are you using the latest?

Another option is what Vlad did:
Disable the plugin and do a deployment (this should remove all the stuff related to the warmer)
Then enable the plugin and do a deployment (this should create the new plugin with the new lambda).

This should work out of the box but that's definitely a way to force it.

**Comment by rbjoshi** [comment]
@juanjoDiaz 
I am using 
"serverless": "1.35.1",
"serverless-domain-manager": "^2.6.5",
"serverless-plugin-warmup": "^3.0.5-rc.1",
"serverless-log-forwarding": "^1.3.0"

and getting the below error while deploying
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: WarmUpPluginLambdaFunction - The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 5211b05e-0bd4-40d7-9555-9aac489053d0).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.35.1

I tried to upgrade the versions but than it cannot find the warmer itself

Thanks,

**Comment by juanjoDiaz** [comment]
So you are in version 3.0.5-rc.1 while the plugin latest version is currently 4.7.0-rc.1.

4.0.0-rc.1 was updated to node 8.10
4.6.3-rc.1 was updated to node 10.x

**Comment by rbjoshi** [comment]
I tired that and getting this error and serverless.yml plugins part has serverless-plugin-warmup entry.
cross-env NODE_ENV=staging sls deploy -s staging
 
  Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-plugin-warmup" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.35.1

**Comment by juanjoDiaz** [comment]
The error seems to indicate that the npm package for the plugin is not properly installed.

**Comment by rbjoshi** [comment]
I am getting the above error when upgrading the serverless warmup plugin from ^3.0.5-rc.1 to newer version. I tried to uninstall the plugin and install it again still happening

**Comment by juanjoDiaz** [comment]
How are you uninstalling the plugin?
Have you checked from the console, that the plugin lambda is actually removed?

**Comment by rbjoshi** [comment]
I uninstalled the plugin and deploy it on AWS and it was successful than installed it using 
npm install serverless-plugin-warmup@^4.0.0-rc.1 --save-dev and getting the error again if I use 3.0.5-rc.1 than getting node 6.10 is no longer supported error.
