### ISSUE TITLE
Should the plugin be gitignored?

### ISSUE THREAD

**Issue by sebastianDejoy** [FidelLimited/serverless-plugin-warmup#174]
Hey, thanks for this amazing plugin. I wonder if it's a good practice to add a  `.gitignore` entry to the _warmup folder so this would not be pushed into my code repo. Thanks.

**Comment by juanjoDiaz** [comment]
Hi @sebastianDejoy ,

Yes. I think that it's a good practice to `.gitignore` every generated folder/file.

**Comment by sebastianDejoy** [comment]
Thanks @juanjoDiaz , i will include it in `.gitignore` file

**Comment by juanjoDiaz** [comment]
👍 

Also, remember that, if you have already pushed the `_warmup` folder you need to remove it and push again or the folder will still be in the repo.

Closing this. Feel free to reopen if needed.
