### ISSUE TITLE
Custom Events Schedule Cron will not deploy

### ISSUE THREAD

**Issue by lsbyerley** [FidelLimited/serverless-plugin-warmup#193]
I'm setting up a custom events schedule for one of my lambda functions. I've setup the cron to run `Every 5 minutes, between 09:00 AM and 10:59 PM, Monday through Sunday, only in January through April, November, and December` and followed the Cloudwatch Cron Expression rules here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions

Based on the readme, I should setup the custom schedule like so:

    custom:
      warmup:
        events:
          - schedule: cron(0/5 9-22 * 1-4,11,12 1-7 ?)

However, I keep getting an error: `  An error occurred: WarmUpPluginEventsRuleSchedule1 - Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: adce114a-b59b-40bb-ad98-ef554712538e).`

I feel I've followed all the rules correctly, so please let me know if I have not.

**Comment by juanjoDiaz** [comment]
The error doesn't come from the plugin bit directly from AWS because the expression is invalid.

A quick look at the documentation tells me that `?` is not supported for the year portion.
So maybe `schedule: cron(0/5 9-22 * 1-4,11,12 * *)`?

**Comment by lsbyerley** [comment]
@juanjoDiaz Turns out, leaving off the extra `*` and this rule: `You can't specify the Day-of-month and Day-of-week fields in the same cron expression. If you specify a value (or a *) in one of the fields, you must use a ? (question mark) in the other.` was causing the error. 

This one works, thank you for your help!

    cron(0/5 9-22 * 1-4,11,12 ? *)
