### ISSUE TITLE
The difference between this plugin and cloudwatch event

### ISSUE THREAD

**Issue by chengjia080787** [FidelLimited/serverless-plugin-warmup#194]
Hi,

This plugin is amazing and I absolutely like it. Thanks so much for your effort.

I just have a stupid question about this plugin, which is, what is the difference between this plugin and the cloudwatch event?

Previously what I did was I setup a cloudwatch event to ping the lambda every 5 minutes. Is there any other benefits I can get from changing to use this plugin instead?

Tons of thanks

CJ

**Comment by juanjoDiaz** [comment]
The idea is the same.

However, this plugin has some advantages:
* Easy configuration and good integration with the serverless framework
* Option to warm up your lambdas immediately after deploying
* Support concurrent lambdas warmup
* Produce logs of the lambda invocations
* Total control of the payload

**Comment by chengjia080787** [comment]
> The idea is the same.
> 
> However, this plugin has some advantages:
> 
> * Easy configuration and good integration with the serverless framework
> * Option to warm up your lambdas immediately after deploying
> * Support concurrent lambdas warmup
> * Produce logs of the lambda invocations
> * Total control of the payload

Thanks for you answer. It's solved!
