### ISSUE TITLE
How do I access the "source" object in Java?

### ISSUE THREAD

**Issue by RoniFinTech** [FidelLimited/serverless-plugin-warmup#203]
I'm looking to run the following command in my Java handler():
 if (event.source === 'serverless-plugin-warmup')

Is it possible?

**Comment by juanjoDiaz** [comment]
It should be.
I don't use Java, but based on the examples like https://github.com/serverless/examples/blob/master/aws-java-simple-http-endpoint/src/main/java/com/serverless/Handler.java it seems that the `event` is your `input` which seems to typically be a `Map<String, Object>`.

So to get the source property you should do something like:
```java
if (input.get("source").equals("serverless-plugin-warmup"))
```

maybe you need to cast `input.get("source")` to `String`.

Let me know if this helps.

**Comment by juanjoDiaz** [comment]
Closing for a lack of response.
Feel free to reopen.
