### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by zemacnica** [FidelLimited/serverless-plugin-warmup#212]
Hi,

I have problem to deploy due to syntax error in plugin

lambda node 12.x
serverles 1.52.2
plugin 4.9.0

Syntax Error -------------------------------------------
 
 /builds/.../node_modules/serverless-plugin-warmup/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
  } catch {

**Comment by juanjoDiaz** [comment]
That's a duplicate of #211.

You can read my answer there.
In short, you should update your development or CI environment (where you run the serverless commands) to node 10. Node 8 was EOL'd last December.
