### ISSUE TITLE
Feature Request : customize event source

### ISSUE THREAD

**Issue by shahbour** [FidelLimited/serverless-plugin-warmup#26]
I am using java lambda functions with spring-boot that do handle all the serialize / deserialize   , so having a dynamic event source that can be set in configuration will help utilize it better.

**Comment by goncaloneves** [comment]
Yes, something that could be easily added. I don't have time to new feats in the near future. PR is welcomed 👍

**Comment by shahbour** [comment]
Ok , i am already preparing a PR , I am thinking in doing it per Function ,
so instead of returning function name return functionObject.name

**Comment by goncaloneves** [comment]
@shahbour was this PR discarded? 🤔

**Comment by shahbour** [comment]
No I did not have time to finalize it.

**Comment by goncaloneves** [comment]
Alright. 👍 
I will keep this open if you get a chance one day. 😏

**Comment by codemoomba** [comment]
Sorry about the commit confusion. I had issues getting git to recognize my personal account.
