### ISSUE TITLE
THANK YOU FOR MAKING THIS!

### ISSUE THREAD

**Issue by justrossthings** [FidelLimited/serverless-plugin-warmup#33]
MFW to Amazon when using this:

![image](https://user-images.githubusercontent.com/8374514/30796510-b7a205b4-a215-11e7-93c5-241062816015.png)

**Comment by goncaloneves** [comment]
@justrossthings thanks man 😎 

😁 😇

**Comment by ahharu** [comment]
Pop Team Epic!
