### ISSUE TITLE
region via flag doesn't get detected 

### ISSUE THREAD

**Issue by gdi2290** [FidelLimited/serverless-plugin-warmup#38]
`sls deploy -s staging -v -r us-west-2` 
our region is set via cli and not the config so by default it's deploying to east rather than west

**Comment by joelbowen** [comment]
+1 I haven't been able to get my warmup plugin to target the proper region when setting that region by cli.

**Comment by gdi2290** [comment]
I fixed this by making sure it's in the serverless.yml
