### ISSUE TITLE
two repos one warmup function

### ISSUE THREAD

**Issue by gdi2290** [FidelLimited/serverless-plugin-warmup#40]
we have two repos and would like to reuse the same warmup function to warm up

**Comment by juanjoDiaz** [comment]
I would say that this is the same problem as in #41, warming up multiple projects/deployments .

I see this plugin as a way to facilitate keeping warm a serverless project. For multiple projects/deployments you would need one warmup function per project.

If that's really a problem for you, you could simply copy the warmup function from the source code of this project and create your own warmup function. If you want more automation you can probably create a script using AWS SDK to get the existing lambdas in your account and then warm them.

**Comment by gdi2290** [comment]
looking into the source code it seemed easier completing the other issue compared to this one. It's easy enough just to copy the source and manually include the function names. I can add these features but it would require rewriting the repo and current API

**Comment by goncaloneves** [comment]
I don't think this will ever be done as warmup plugin is meant to exist within a Serverless Cloudformation deployed stack.

Cross region/stack would increase complexity one order of magnitude, without much value in return.

As @juanjoDiaz said, you can always pick this up manually and run your own warmup function.

**Comment by gdi2290** [comment]
koo, yeah I'll make one later when it becomes more of an issue
