### ISSUE TITLE
Feature Request: run a warmup on functions immediately after deployment

### ISSUE THREAD

**Issue by jonathankeebler** [FidelLimited/serverless-plugin-warmup#44]
Currently if you set the warmup time interval to 5 minutes, and you deploy your Serverless project, the first time a warmup runs will be 5 minutes after the deployment. If you execute your newly deployed Lambda function manually within the first 5 minutes after deployment, it will have a cold start.

Perhaps the plugin could run all the Lambdas from localhost immediately after the ç stack update is finished i.e. after "Serverless: Stack update finished..." in the Serverless logs

**Comment by juanjoDiaz** [comment]
You just need to set the `prewarm` option to true and your lambdas will be warmed up immediately after deployment (see the readme).

**Comment by jonathankeebler** [comment]
Thanks!
