### ISSUE TITLE
Warm Lambda not being utilized.

### ISSUE THREAD

**Issue by murtyjones** [FidelLimited/serverless-plugin-warmup#56]
I recognize that this is slightly out of scope for what this library accomplishes, but I'm noticing that even with successful warmups being executed every 5 minutes, my Lambda containers tend not to be reused. I'm regularly seeing startup times of 2-3 seconds when calling from a different event source (e.g. going thru API Gateway).

Seems from [this answer](https://stackoverflow.com/a/46780884/5796602) that it's common to see a warm Lambda container not being reused when being called from a different event source than the one used to warm the Lambda.

Just wondering if this is a common occurrence and if there is any way to increase the likelihood of container reuse when calling from a different even source.

**Comment by juanjoDiaz** [comment]
AFAIK AWS is 100% opaque about how Lambda containers are reused so all we can do is take our best guesses to avoid cold start.

In my case, this plugin has consistently reduce cold startups.
