### ISSUE TITLE
Generating a CloudWatch log, not deleted in "sls remove".

### ISSUE THREAD

**Issue by cdichiara** [FidelLimited/serverless-plugin-warmup#57]
Hi, nice plugin. :)

I believe you're generating a CloudWatch log "<service>-<stage>-warmup", but it's not registered with the CloudFormation stack, so when you uninstall the deployment it persists and interferes with redeployment, I think.

**Comment by alvarodms** [comment]
I'm also having issues with redeployment.

Getting the following error:

```
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: WarmUpPluginLogGroup - /aws/lambda/test-api-warmup-plugin already exists.
```

I had to manually delete that log group on CloudWatch.

**Comment by goncaloneves** [comment]
@cdichiara @alvarodms What version were you using, 3.6.0?

**Comment by goncaloneves** [comment]
It should have been the options bug from 3.6.0. Did a quick `deploy` / `remove` test and it's working fine with latest `3.6.1` version.

**Comment by cdichiara** [comment]
Oh, thanks, I just updated - I was way back at 3.3.0, that's probably it.

**Comment by sashokbg** [comment]
I am experiencing this problem with 3.6.2-rc.1 any advise ?

**Comment by juanjoDiaz** [comment]
Any reason to not update to the latest version 4.4.3-rc.1?

**Comment by antoniuslin** [comment]
```  
Serverless Error ---------------------------------------

  An error occurred: WarmUpPluginLogGroup - /aws/lambda/lambda-warmer already exists in stack arn:aws:cloudformation:us-e...
```

Bump.
Hello. I'm still experiencing this issue using `"serverless-plugin-warmup": "^4.5.3-rc.1",`. I encountered the issue during a re-deploy. Is there a plan on the way?
Thank you.

**Comment by juanjoDiaz** [comment]
Hi @antoniuslin,

quick googling shows me that this is a known problem of Serverless when using multiple stages (https://github.com/serverless/serverless/issues/5057)
Can you take a look at that and let me know if it helps?

**Comment by antoniuslin** [comment]
Hi @juanjoDiaz, 

I can confirm that multiple stages of deployment. My issue seems to have disappeared (resolved?) when specifying the service & stage in the lambda warmer config block itself as you hinted from the link. E.g.

```
  warmup:
    enabled: true
    ...
    # specified
    name: ${self:service}-${opt:stage}-lambda-warmer
    # instead of the prior
    # name: 'lambda-warmer'
    ...
    timeout: 60
```

It resulted in a unique lambda log group per stage for the service.
Thanks much!

**Comment by juanjoDiaz** [comment]
That's odd since that should be the default name anyway.
And the name `lambda-warmer` is nowhere in the codebase.
Any idea of where was it coming from?

**Comment by antoniuslin** [comment]
Honestly, I don't remember and I'd just sooner chalk it up to **my not** RTFM & hasty copypasta from some article about this nice & nifty plugin somewhere. If I had just spent a couple of proper minutes reading the [`README.md`](https://github.com/FidelLimited/serverless-plugin-warmup/blob/master/README.md#L42), I would've found the info:
> name (default ${service}-${stage}-warmup-plugin)
