### ISSUE TITLE
custom variableSyntax fails to deploy in version 3.6.0-rc.1

### ISSUE THREAD

**Issue by kristianperkins** [FidelLimited/serverless-plugin-warmup#59]
with a `variableSyntax` in serverless.yml set to:

    provider:
      variableSyntax: "\\${{([\\s\\S]+?)}}"

Deployments using serverless-plugin-warmup@3.6.0-rc.1 fails with the error:

```
  Serverless Error ---------------------------------------

  The stack service name "serverless-service-${{env:SERVERLESS_STAGE}}" is not valid. A service name should only contain alphanumeric (case sensitive) and hyphens. It should start with an alphabetic character and shouldn't exceed 128 characters.
```

The same deployment using serverless-plugin-warmup@3.5.0-rc.1 deploys successfully.

**Comment by kristianperkins** [comment]
With a function defined in serverless.yml like:

```functions:
  function-name:
    warmup: true
 ```

this also appears in the serverless deploy logs:

    Serverless: WarmUP: serverless-service-${{env:SERVERLESS_STAGE}}-function-name

indicating that the warmup plugin is probably not resolving the variables when a custom `variableSyntax` is used.

**Comment by OlzhasAlexandrov** [comment]
I report the same issue. Environment variables stopped being passed.

**Comment by goncaloneves** [comment]
Sorry for late merge. Should be fine now, I've tested and all looks good. Let me know if you still have issues with 3.6.1.
