### ISSUE TITLE
Companion Middy middleware

### ISSUE THREAD

**Issue by alexdrans** [FidelLimited/serverless-plugin-warmup#67]
Hi,

I have created a [Middy](https://github.com/middyjs/middy) middleware to be used with this plugin. You can find it [here](https://github.com/alexdrans/middy-middleware-warmup). With the middleware you won't have to manually handle the warmup request.

Thanks for creating this plugin, and I hope somebody finds my middleware useful!

Alex

**Comment by goncaloneves** [comment]
Cool Alex. Thanks for letting us know.
