### ISSUE TITLE
Circular dependency when using package: artifact

### ISSUE THREAD

**Issue by josephryanwynne** [FidelLimited/serverless-plugin-warmup#70]
When we build a zip of our project we need the **_warmup** directory to exist with the correct configurations so that we can include it in the zip to be deployed. This directory seems to get created only when running the "sls package" command, which in turn requires our zip file to exist. It would be nice if there was a way to generate the contents of the _warmup directory by some other means, so that I can create this, then package everything into my deployable zip, and then use "sls deploy".

I can't see a decent workaround at the moment. My deployment script is currently running "sls package" before anything else, and ignoring the error which is caused by the package artifact not having already been built.

**Comment by marcfielding1** [comment]
If I'm understanding this correctly this sounds like more a serverless framework PR than here? It's a problem with the way deploy/package works? Excuse me if I've misunderstood though?

**Comment by marcfielding1** [comment]
Actually, hold on if you go down the Readme is this what you're looking for?
https://github.com/FidelLimited/serverless-plugin-warmup#artifact

**Comment by josephryanwynne** [comment]
@marcfielding1 I guess whether it's a serverless issue or plugin issue possibly depends on where the best solution fits. I am only an end user of serverless (never contributed) and assumed that as this issue is only affecting our use of this plugin, that it was a plugin issue. I thought a solution might be to provide a plugin task which prepares the files so I could just break this into steps: Build plugins (ie. warmup plugin) > Build Artifact (contains multiple java lambdas AND the prepared _warmup plugin) > sls deploy our complete artifact which now contains our stuff AND the warmup plugin. That cleanFolder option doesn't seem to help. If I were to run sls package before I build my artifact then the package command throws an error becuase I have not yet created the zip file which I ultimately want to deploy. I think @juanjoDiaz's response is on track and seems like he's already trying to get this fixed.

@juanjoDiaz This does seem like a dupe of that issue. We are bundling our java lambdas into a zip file using Gradle. If I correctly understood what you are trying to implement in serverless framework itself... I should be able to specify my artifact containing my application logic at the top level (same as I currently do), and then define the warmup plugin as distinct individually packaged function. This would mean that my zip no longer needs to contain the _warmup plugin, so I can just do my artifact creation, sls package, sls deploy? And I could omit the sls package as I believe that will happen as part of deploy process?

**Comment by juanjoDiaz** [comment]
Closing this. Let's follow up on #25!

My fix for this issue was just merged to the serverless repo and should be available when they release next!
