### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by juanjoDiaz** [FidelLimited/serverless-plugin-warmup#83]
Related to #15 

It's a bit of a pain in the neck to work on the plugin and have to test all the cases manually.
Some unit or integration tests will help a lot.

I don't have time for this at the moment. So just leaving here in case we can get a champion to contribute 🙂

**Comment by goncaloneves** [comment]
Another option is Jest which brings code coverage out of the box.

**Comment by juanjoDiaz** [comment]
Damn! I thought I drop a message here yesterday. It seems like it didn't send.

I also vote for Jest. Batteries included and more performant.
