### ISSUE TITLE
Strange IAM permission 

### ISSUE THREAD

**Issue by gs-jackal** [FidelLimited/serverless-plugin-warmup#88]
I'm trying to understand why does this plugin need following permissions?

```
- ec2:CreateNetworkInterface
- ec2:DescribeNetworkInterfaces
- ec2:DetachNetworkInterface
- ec2:DeleteNetworkInterface
```

**Comment by juanjoDiaz** [comment]
Those are needed if the lambda is deployed to a VPC.
You can read more here: https://docs.aws.amazon.com/lambda/latest/dg/vpc.html

> The Lambda function execution role must have permissions to create, describe and delete ENIs. AWS Lambda provides a permissions policy, AWSLambdaVPCAccessExecutionRole, with permissions for the necessary EC2 actions (ec2:CreateNetworkInterface, ec2:DescribeNetworkInterfaces, and ec2:DeleteNetworkInterface) that you can use when creating a role. You can review the policy in the IAM console. Do not delete this role immediately after your Lambda function execution. There is a delay between the time your Lambda function executes and ENI deletion. If you do delete the role immediately after function execution, you are responsible for deleting the ENIs.

**Comment by ssteo** [comment]
Thanks @juanjoDiaz  for the clarification.
If I'm not deploying the Lambda to VPC, would omitting those IAM permission still work?

**Comment by juanjoDiaz** [comment]
It should work AFAIK.

**Comment by ssteo** [comment]
Cool, thanks for the clarification.
